name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-transaction-service:
    name: Build Transaction Service
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: |
          mvn clean compile -DskipTests
          echo "Transaction Service compiled successfully"

      - name: Run Tests
        run: |
          mvn test
          echo "Transaction Service tests passed"

      - name: Package
        run: |
          mvn package -DskipTests
          echo "Transaction Service packaged"
